environment:
    matrix:
    #node.js
    _nodejs_version: "4.3"

install:
- ps: Install-Product node $env:nodejs_version

- npm install

test_script:
    - node --version
    - npm --version
    -npm test

build: off